import './globals.css'

import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { StarsCanvas, Stars } from "../components/canvas/beans";
import './script'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children}) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <div className='z-20 relative'>
          <Navbar />
        </div>
        <div className="z-0 flex h-screen w-screen fixed top-0">
          <StarsCanvas />
        </div>
        <div className='z-10 relative'>
        {children}
        </div>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"/>
        
      </body>
      {/* <script src='./script.jsx'></script> */}
    </html>
  )
}
