import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { StarsCanvas, Stars } from "../components/canvas/beans";
import './script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div>
          <Navbar />
        </div>
        <div className="z-0 flex h-screen w-screen fixed">
          <StarsCanvas />
        </div>

        {children}

      </body>
      {/* <script src='./script.jsx'></script> */}
    </html>
  )
}
