
import './globals.css'

import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { StarsCanvas, Stars } from "../components/canvas/beans";
import './script'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Launam Coffee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
  <head></head>
      <body className={inter.className}>

        <div className="z-0 flex h-screen w-screen fixed top-0">
          <StarsCanvas />
        </div>
        <div className='relative top-0 z-10 '>
          {children}
        </div>


        
      </body>
    </html>
  )
}
